# Site settings
title: Stolpersteine Heilbronn
email: lukas@himsel.me
description: ""
baseurl: "/stolpersteine"
url: "https://opendata-heilbronn.github.io"

# Build settings
markdown: kramdown
permalink: pretty

exclude: ["_data/test.json", "_data/data.json"]

collections:
    list:
        title: Liste
        output: true
        permalink: "/list/:name:output_ext"
    actions:
        title: Aktionen
        output: true
        permalink: "/aktionen/:name:output_ext"

defaults:
- scope:
    path: ''
    type: actions
  values:
    layout: action
- scope:
    path: ''
    type: list
  values:
    layout: list
    title:
    kopfzeile: "HIER WOHNTE"
    name: "NAME, VORNAME"
    name_zusatz: ""
    geb_name: ""
    zusatz1: ""
    jg: ""
    deportiert: ""
    ermordet_zeile1: "ERMORDET IN"
    ermordet_zeile2: ""
    zusatz2: ""