# Site settings
title: Stolpersteine Heilbronn
email: lukas@himsel.me
description: ""
baseurl: "/stolpersteine"
url: "https://opendata-heilbronn.github.io"

# Build settings
markdown: kramdown
permalink: pretty

exclude: ["_data/test.json", "_data/data.json"]

collections:
    list:
        title: Liste
        output: true
        permalink: "/list/:name:output_ext"
    actions:
        title: Aktionen
        output: true
        permalink: "/aktionen/:name:output_ext"

defaults:
- scope:
    path: ''
    type: actions
  values:
    layout: action
    pdf: true
- scope:
    path: ''
    type: item
  values:
    layout: item
    title:
    steine: [
        [
            "HIER WOHNTE",
            "VORNAME NACHNAME",
            "",
            "",
            "1900",
            "DEPORTIERT JAHR",
            "ERMORDET IN",
            "ORT",
            ""
        ]
    ]

gems:
  - jekyll-assets
  - jekyll-pdf